/*
The MIT License (MIT)

Copyright (c) 2016 Lancaster University, UK.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "DeviceConfig.h"
#include "nRF51DK.h"

CodalDevice device;

/**
  * Constructor.
  *
  * Create a representation of a nRF51DK device, which includes member variables
  * that represent various device drivers used to control aspects of the micro:bit.
  */

    //serial(USBTX, USBRX),
    //storage(),
    //i2c(I2C_SDA0, I2C_SCL0),
    //messageBus(),
    //display(DEVICE_ID_DISPLAY, map),
    //buttonAB(DEVICE_ID_BUTTON_A,DEVICE_ID_BUTTON_B, DEVICE_ID_BUTTON_AB),
    //bleManager(storage),
    //radio(),
    //ble(NULL)

nRF51DK::nRF51DK() :
    io(),
    messageBus(),
    buttonA(DEVICE_PIN_BUTTON_A, DEVICE_ID_BUTTON_A, DEVICE_BUTTON_ALL_EVENTS, PullUp),
    buttonB(DEVICE_PIN_BUTTON_B, DEVICE_ID_BUTTON_B, DEVICE_BUTTON_ALL_EVENTS, PullUp)
{
    // Clear our status
    status = 0;
}

/**
  * Post constructor initialisation method.
  *
  * This call will initialised the scheduler, memory allocator and Bluetooth stack.
  *
  * This is required as the Bluetooth stack can't be brought up in a
  * static context i.e. in a constructor.
  *
  * @code
  * uBit.init();
  * @endcode
  *
  * @note This method must be called before user code utilises any functionality
  *       contained by uBit.
  */
void nRF51DK::init()
{
    if (status & NRF51DK_INITIALIZED)
        return;

#if CONFIG_ENABLED(DEVICE_HEAP_ALLOCATOR)
    // Bring up a nested heap allocator.
    device_create_nested_heap(DEVICE_NESTED_HEAP_SIZE);
#endif

    // Bring up fiber scheduler.
    scheduler_init(messageBus);

    // Seed our random number generator
    //seedRandom();

    // Create an event handler to trap any handlers being created for I2C services.
    // We do this to enable initialisation of those services only when they're used,
    // which saves processor time, memeory and battery life.
    messageBus.listen(DEVICE_ID_MESSAGE_BUS_LISTENER, DEVICE_EVT_ANY, this, &nRF51DK::onListenerRegisteredEvent);

    status |= NRF51DK_INITIALIZED;

    // Attempt to bring up a second heap region, using unused memory normally reserved for Soft Device.
#if CONFIG_ENABLED(DEVICE_HEAP_ALLOCATOR) && CONFIG_ENABLED(DEVICE_HEAP_REUSE_SD)
#if CONFIG_ENABLED(DEVICE_BLE_ENABLED)
    device_create_heap(DEVICE_SD_GATT_TABLE_START + DEVICE_SD_GATT_TABLE_SIZE, DEVICE_SD_LIMIT);
#else
    device_create_heap(DEVICE_SRAM_BASE, DEVICE_SD_LIMIT);
#endif
#endif

}

/**
  * A listener to perform actions as a result of Message Bus reflection.
  *
  * In some cases we want to perform lazy instantiation of components, such as
  * the compass and the accelerometer, where we only want to add them to the idle
  * fiber when someone has the intention of using these components.
  */
void nRF51DK::onListenerRegisteredEvent(DeviceEvent evt)
{
    switch(evt.value)
    {
        case DEVICE_ID_BUTTON_AB:
            // A user has registered to receive events from the buttonAB multibutton.
            // Disable click events from being generated by ButtonA and ButtonB, and defer the
            // control of this to the multibutton handler.
            //
            // This way, buttons look independent unless a buttonAB is requested, at which
            // point button A+B clicks can be correclty handled without breaking
            // causal ordering.
            buttonA.setEventConfiguration(DEVICE_BUTTON_SIMPLE_EVENTS);
            buttonB.setEventConfiguration(DEVICE_BUTTON_SIMPLE_EVENTS);
  //          buttonAB.setEventConfiguration(DEVICE_BUTTON_ALL_EVENTS);
            break;
    }
}
